### PR TITLE
Prettified Output Data

### PR DESCRIPTION
**Pull request by iifeoluwa**
Cleaned up code so data would be a little more presentable.

### CODE REVIEW

**Comment by iifeoluwa** [comment]
Forgot to assign this to you @unicodeveloper
Kindly review.

**Comment by unicodeveloper** [comment]
Please can you add a snapshot of how the output data looks like now here @iifeoluwa ?

**Comment by iifeoluwa** [comment]
Alright, I've attached before and after image. @unicodeveloper 

**Before**
before

**After**
after

**Comment by unicodeveloper** [comment]
Awesome @iifeoluwa . Thanks, I'll merge this in right now. Btw I plan to extract each of them individually tho so that it can be an associative array where stuffs like `PlateNumber`, `Owner Name`, `Color`, `Model` etc are the keys

**Pull request merged**
